export const products = [
  {
    id: 1,
    category: "Accessories",
    title: "Mouse Logitech M331",
    stock: 62,
    price: 300000,
    description: "Mouse Wireless Alytech AL - Y5D, hadir dengan desain 3 tombol mouse yang ringan dan mudah dibawa. Mouse ini menggunakan frekuensi radio 2.4GHz (bekerja hingga jarak 10m) dan fitur sensor canggih optik pelacakan dengan penerima USB yang kecil. Mouse ini didukung oleh 1x baterai AA (hingga 12 bulan hidup baterai). mendukung sistem operasi Windows 7,8, 10 keatas, Mac OS X 10.8 atau yang lebih baru dan sistem operasi Chrome OS.",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1365&q=80",
  },
  {
    id: 2,
    category: 'Accessories',
    title: "Logitech Mk120",
    stock: 200,
    price: 700000,
    description: "Keybooad In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
  },
  {
    id: 3,
    category: 'Monitor',
    title: "Hp P22 22 inch",
    stock: 98,
    price: 2000000,
    description: "Monitor In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://images.unsplash.com/photo-1551645120-d70bfe84c826?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
  },
  {
    id: 4,
    category: "Laptop",
    title: "Macbook Air 3",
    stock: 20,
    price: 1000000,
    description: "Laptop In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
  },
  {
    id: 5,
    category: 'Webcam',
    title: "Logitech HD Cam",
    stock: 70,
    price: 400000,
    description: "Webcamp In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://images.unsplash.com/photo-1626581806599-d12b0bbd4225?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
  },
  {
    id: 6,
    category: 'Speaker',
    title: "Harman Kardon",
    stock: 23,
    price: 578000,
    description: "Speaker In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://id-test-11.slatic.net/p/566aa1cec80a0014bbd79f37ad3ca025.jpg",
  },
  {
    id: 7,
    category: 'Speaker',
    title: "Bose SoundLink",
    stock: 14,
    price: 578000,
    description: "Speaker In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available",
    image: "https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//91/MTA-1564471/bose_bose-soundlink-color-ii-bluetooth-speaker---black_full02.jpg",
  },
];

